package com.leadics.poll.dto;
// Generated Sep 3, 2018 10:00:04 PM by Hibernate Tools 5.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by hbm2java
 */
public class Questions implements java.io.Serializable {

	private Integer id;
	private int pollId;
	private String question;
	private Boolean status;
	private String ans1;
	private int cnt1;
	private String ans2;
	private int cnt2;
	private String ans3;
	private int cnt3;
	private String ans4;
	private int cnt4;
	private String ans5;
	private int cnt5;
	private int vote;
	private Set votes = new HashSet(0);

	public Questions() {
	}

	public Questions(int pollId, int cnt1, int cnt2, int cnt3, int cnt4, int cnt5, int vote) {
		this.pollId = pollId;
		this.cnt1 = cnt1;
		this.cnt2 = cnt2;
		this.cnt3 = cnt3;
		this.cnt4 = cnt4;
		this.cnt5 = cnt5;
		this.vote = vote;
	}

	public Questions(int pollId, String question, Boolean status, String ans1, int cnt1, String ans2, int cnt2,
			String ans3, int cnt3, String ans4, int cnt4, String ans5, int cnt5, int vote, Set votes) {
		this.pollId = pollId;
		this.question = question;
		this.status = status;
		this.ans1 = ans1;
		this.cnt1 = cnt1;
		this.ans2 = ans2;
		this.cnt2 = cnt2;
		this.ans3 = ans3;
		this.cnt3 = cnt3;
		this.ans4 = ans4;
		this.cnt4 = cnt4;
		this.ans5 = ans5;
		this.cnt5 = cnt5;
		this.vote = vote;
		this.votes = votes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPollId() {
		return this.pollId;
	}

	public void setPollId(int pollId) {
		this.pollId = pollId;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public String getAns1() {
		return this.ans1;
	}

	public void setAns1(String ans1) {
		this.ans1 = ans1;
	}

	public int getCnt1() {
		return this.cnt1;
	}

	public void setCnt1(int cnt1) {
		this.cnt1 = cnt1;
	}

	public String getAns2() {
		return this.ans2;
	}

	public void setAns2(String ans2) {
		this.ans2 = ans2;
	}

	public int getCnt2() {
		return this.cnt2;
	}

	public void setCnt2(int cnt2) {
		this.cnt2 = cnt2;
	}

	public String getAns3() {
		return this.ans3;
	}

	public void setAns3(String ans3) {
		this.ans3 = ans3;
	}

	public int getCnt3() {
		return this.cnt3;
	}

	public void setCnt3(int cnt3) {
		this.cnt3 = cnt3;
	}

	public String getAns4() {
		return this.ans4;
	}

	public void setAns4(String ans4) {
		this.ans4 = ans4;
	}

	public int getCnt4() {
		return this.cnt4;
	}

	public void setCnt4(int cnt4) {
		this.cnt4 = cnt4;
	}

	public String getAns5() {
		return this.ans5;
	}

	public void setAns5(String ans5) {
		this.ans5 = ans5;
	}

	public int getCnt5() {
		return this.cnt5;
	}

	public void setCnt5(int cnt5) {
		this.cnt5 = cnt5;
	}

	public int getVote() {
		return this.vote;
	}

	public void setVote(int vote) {
		this.vote = vote;
	}

	public Set getVotes() {
		return this.votes;
	}

	public void setVotes(Set votes) {
		this.votes = votes;
	}

	@Override
	public String toString() {
		return "Questions [id=" + id + ", pollId=" + pollId + ", question=" + question + ", status=" + status
				+ ", ans1=" + ans1 + ", cnt1=" + cnt1 + ", ans2=" + ans2 + ", cnt2=" + cnt2 + ", ans3=" + ans3
				+ ", cnt3=" + cnt3 + ", ans4=" + ans4 + ", cnt4=" + cnt4 + ", ans5=" + ans5 + ", cnt5=" + cnt5
				+ ", vote=" + vote + ", votes=" + votes + "]";
	}

}
